### ISSUE TITLE
wdt reset 

### ISSUE THREAD

**Issue by mrWeles** [fusionps/Arduino_SNMP#1]
Hi!
Thank you for the work you did.
I have a watchdog timer on this line (using ESP12). 
int length = response->serialise(_packetBuffer);
Do you have any ideas how to fix this?

**Comment by 0neblock** [comment]
Hey,
If you can give me the rest of the code you're using I might be able to help.
It can get an error in this stage if the data you are trying to send back is in the wrong format/length.
Can you see if the example sketch works?
