### ISSUE TITLE
addOIDHandler

### ISSUE THREAD

**Issue by AdamPiorko** [fusionps/Arduino_SNMP#3]
Will there be an addOIDHandler function added?
I need to return information on question 1.3.6.1.2.1.1.2.0 which requires the OID data type.

For example:
_snmpget -v 1 -c public <IP> 1.3.6.1.2.1.1.2.0
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.14988.1_

**Comment by 0neblock** [comment]
Hey,

I made a quick addition that enables this in commit #4b7f89ef
snmp.addOIDHandler(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.14988.1");

Let me know if it works.

**Comment by AdamPiorko** [comment]
Something is wrong.
snmp.addOIDHandler(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.**14988**.1");
responds
snmpget -v 1 -c public 192.168.2.186 1.3.6.1.2.1.1.2.0
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.**14988**.1


snmp.addOIDHandler(".1.3.6.1.2.1.1.2.0", ".1.3.6.1.4.1.**52421**.1");
responds
snmpget -v 1 -c public 192.168.2.186 1.3.6.1.2.1.1.2.0
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.**3269**.1

**Comment by 0neblock** [comment]
Hey, 
I noticed this too, it was a problem with the way I was encoding the ASN.1 packets.
Fixed in commit: [#229a7fccf](https://github.com/fusionps/Arduino_SNMP/commit/229a7fccf9abc7bb67e23f7801329397c20cdc90)

**Comment by AdamPiorko** [comment]
It works. Thank you.
