### ISSUE TITLE
Snmp agent working example

### ISSUE THREAD

**Issue by Jimcodom** [fusionps/Arduino_SNMP#5]
Can you advise if your agent is working on the esp32 ? I want to build a simple snmp agent that can be polled via snmp from solar winds with a few sensors and found your GitHub code. Do you have any working snmp agent examples that would support my project?

Any help or advise would be greatly appreciated!

**Comment by 0neblock** [comment]
Hi, there is a working example for an ESP32 here: https://github.com/fusionps/Arduino_SNMP/blob/master/examples/ESP32_SNMP/ESP32_SNMP.ino
Let me know if you have any issues getting it working.

**Comment by Jimcodom** [comment]
Aidan,

 

Thanks so much !!

 

I will get it a try…

 

jim

**Comment by Jimcodom** [comment]
Aidan,

 

Does the library support multiple OID’s so I can store multiple data value types? Temp Location 1, Temp Location 2, Alarm 1, etc…?

 

jim

**Comment by 0neblock** [comment]
Hey, sorry for the late reply.
Yes you can add multiple handlers of different types to respond to many different OIDs.
