### ISSUE TITLE
SNMP traps

### ISSUE THREAD

**Issue by demakovnik** [fusionps/Arduino_SNMP#6]
Hello!
How can I send SNMP-traps from my ESP8266 board via Arduino_SNMP library?

**Comment by Augustine-Park** [comment]
Hi! 
Any one has a example source code how to operate SNMP trap function?
Please let me know how to do.

**Comment by 0neblock** [comment]
Hi,

Apologies for the delay, there is now an example for sending an SNMP Trap.
bbca0cf508fac41106200e18ab2346a477b50e30
Please let me know if you have any problems.

Thanks.
